# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_calibration.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Calibration(object):
    def setupUi(self, Calibration):
        Calibration.setObjectName(_fromUtf8("Calibration"))
        Calibration.resize(1116, 849)
        self.horizontalLayout_3 = QtGui.QHBoxLayout(Calibration)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.h_gVShowRealImg = GraphicsView(Calibration)
        self.h_gVShowRealImg.setMinimumSize(QtCore.QSize(500, 500))
        self.h_gVShowRealImg.setObjectName(_fromUtf8("h_gVShowRealImg"))
        self.widget = QtGui.QWidget(self.h_gVShowRealImg)
        self.widget.setGeometry(QtCore.QRect(210, 260, 120, 80))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_2.addWidget(self.h_gVShowRealImg)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_grabImg = QtGui.QPushButton(Calibration)
        self.pushButton_grabImg.setMinimumSize(QtCore.QSize(120, 60))
        self.pushButton_grabImg.setMaximumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.pushButton_grabImg.setFont(font)
        self.pushButton_grabImg.setCheckable(True)
        self.pushButton_grabImg.setObjectName(_fromUtf8("pushButton_grabImg"))
        self.horizontalLayout.addWidget(self.pushButton_grabImg)
        self.pushButton_save = QtGui.QPushButton(Calibration)
        self.pushButton_save.setMinimumSize(QtCore.QSize(120, 60))
        self.pushButton_save.setMaximumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.horizontalLayout.addWidget(self.pushButton_save)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(8, -1, -1, -1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_1 = QtGui.QLabel(Calibration)
        self.label_1.setMinimumSize(QtCore.QSize(100, 50))
        self.label_1.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.label_1.setFont(font)
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.gridLayout.addWidget(self.label_1, 0, 0, 1, 1)
        self.standard_angle_x = QtGui.QLabel(Calibration)
        self.standard_angle_x.setMinimumSize(QtCore.QSize(100, 50))
        self.standard_angle_x.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.standard_angle_x.setFont(font)
        self.standard_angle_x.setText(_fromUtf8(""))
        self.standard_angle_x.setObjectName(_fromUtf8("standard_angle_x"))
        self.gridLayout.addWidget(self.standard_angle_x, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(Calibration)
        self.label_2.setMinimumSize(QtCore.QSize(100, 50))
        self.label_2.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.actual_angle_x = QtGui.QLabel(Calibration)
        self.actual_angle_x.setMinimumSize(QtCore.QSize(100, 50))
        self.actual_angle_x.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.actual_angle_x.setFont(font)
        self.actual_angle_x.setText(_fromUtf8(""))
        self.actual_angle_x.setObjectName(_fromUtf8("actual_angle_x"))
        self.gridLayout.addWidget(self.actual_angle_x, 0, 3, 1, 1)
        self.label_3 = QtGui.QLabel(Calibration)
        self.label_3.setMinimumSize(QtCore.QSize(100, 50))
        self.label_3.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.standard_angle_y = QtGui.QLabel(Calibration)
        self.standard_angle_y.setMinimumSize(QtCore.QSize(100, 50))
        self.standard_angle_y.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.standard_angle_y.setFont(font)
        self.standard_angle_y.setText(_fromUtf8(""))
        self.standard_angle_y.setObjectName(_fromUtf8("standard_angle_y"))
        self.gridLayout.addWidget(self.standard_angle_y, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(Calibration)
        self.label_4.setMinimumSize(QtCore.QSize(100, 50))
        self.label_4.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.actual_angle_y = QtGui.QLabel(Calibration)
        self.actual_angle_y.setMinimumSize(QtCore.QSize(100, 50))
        self.actual_angle_y.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.actual_angle_y.setFont(font)
        self.actual_angle_y.setText(_fromUtf8(""))
        self.actual_angle_y.setObjectName(_fromUtf8("actual_angle_y"))
        self.gridLayout.addWidget(self.actual_angle_y, 1, 3, 1, 1)
        self.label_5 = QtGui.QLabel(Calibration)
        self.label_5.setMinimumSize(QtCore.QSize(100, 50))
        self.label_5.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.standard_angle_z = QtGui.QLabel(Calibration)
        self.standard_angle_z.setMinimumSize(QtCore.QSize(100, 50))
        self.standard_angle_z.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.standard_angle_z.setFont(font)
        self.standard_angle_z.setText(_fromUtf8(""))
        self.standard_angle_z.setObjectName(_fromUtf8("standard_angle_z"))
        self.gridLayout.addWidget(self.standard_angle_z, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(Calibration)
        self.label_6.setMinimumSize(QtCore.QSize(100, 50))
        self.label_6.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 1)
        self.actual_angle_z = QtGui.QLabel(Calibration)
        self.actual_angle_z.setMinimumSize(QtCore.QSize(100, 50))
        self.actual_angle_z.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.actual_angle_z.setFont(font)
        self.actual_angle_z.setText(_fromUtf8(""))
        self.actual_angle_z.setObjectName(_fromUtf8("actual_angle_z"))
        self.gridLayout.addWidget(self.actual_angle_z, 2, 3, 1, 1)
        self.label_7 = QtGui.QLabel(Calibration)
        self.label_7.setMinimumSize(QtCore.QSize(100, 50))
        self.label_7.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.standard_coordinate_x = QtGui.QLabel(Calibration)
        self.standard_coordinate_x.setMinimumSize(QtCore.QSize(100, 50))
        self.standard_coordinate_x.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.standard_coordinate_x.setFont(font)
        self.standard_coordinate_x.setText(_fromUtf8(""))
        self.standard_coordinate_x.setObjectName(_fromUtf8("standard_coordinate_x"))
        self.gridLayout.addWidget(self.standard_coordinate_x, 3, 1, 1, 1)
        self.label_8 = QtGui.QLabel(Calibration)
        self.label_8.setMinimumSize(QtCore.QSize(100, 50))
        self.label_8.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 2, 1, 1)
        self.actual_coordinate_x = QtGui.QLabel(Calibration)
        self.actual_coordinate_x.setMinimumSize(QtCore.QSize(100, 50))
        self.actual_coordinate_x.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.actual_coordinate_x.setFont(font)
        self.actual_coordinate_x.setText(_fromUtf8(""))
        self.actual_coordinate_x.setObjectName(_fromUtf8("actual_coordinate_x"))
        self.gridLayout.addWidget(self.actual_coordinate_x, 3, 3, 1, 1)
        self.label_9 = QtGui.QLabel(Calibration)
        self.label_9.setMinimumSize(QtCore.QSize(100, 50))
        self.label_9.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.standard_coordinate_y = QtGui.QLabel(Calibration)
        self.standard_coordinate_y.setMinimumSize(QtCore.QSize(100, 50))
        self.standard_coordinate_y.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.standard_coordinate_y.setFont(font)
        self.standard_coordinate_y.setText(_fromUtf8(""))
        self.standard_coordinate_y.setObjectName(_fromUtf8("standard_coordinate_y"))
        self.gridLayout.addWidget(self.standard_coordinate_y, 4, 1, 1, 1)
        self.label_10 = QtGui.QLabel(Calibration)
        self.label_10.setMinimumSize(QtCore.QSize(100, 50))
        self.label_10.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 4, 2, 1, 1)
        self.actual_coordinate_y = QtGui.QLabel(Calibration)
        self.actual_coordinate_y.setMinimumSize(QtCore.QSize(100, 50))
        self.actual_coordinate_y.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.actual_coordinate_y.setFont(font)
        self.actual_coordinate_y.setText(_fromUtf8(""))
        self.actual_coordinate_y.setObjectName(_fromUtf8("actual_coordinate_y"))
        self.gridLayout.addWidget(self.actual_coordinate_y, 4, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setContentsMargins(8, -1, -1, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_19 = QtGui.QLabel(Calibration)
        self.label_19.setMinimumSize(QtCore.QSize(100, 50))
        self.label_19.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 0, 0, 1, 1)
        self.sharpness_rate = QtGui.QLabel(Calibration)
        self.sharpness_rate.setMinimumSize(QtCore.QSize(100, 50))
        self.sharpness_rate.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.sharpness_rate.setFont(font)
        self.sharpness_rate.setText(_fromUtf8(""))
        self.sharpness_rate.setObjectName(_fromUtf8("sharpness_rate"))
        self.gridLayout_2.addWidget(self.sharpness_rate, 0, 1, 1, 1)
        self.label_20 = QtGui.QLabel(Calibration)
        self.label_20.setMinimumSize(QtCore.QSize(100, 50))
        self.label_20.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 0, 2, 1, 1)
        self.brightness_rate = QtGui.QLabel(Calibration)
        self.brightness_rate.setMinimumSize(QtCore.QSize(100, 50))
        self.brightness_rate.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.brightness_rate.setFont(font)
        self.brightness_rate.setText(_fromUtf8(""))
        self.brightness_rate.setObjectName(_fromUtf8("brightness_rate"))
        self.gridLayout_2.addWidget(self.brightness_rate, 0, 3, 1, 1)
        self.label_17 = QtGui.QLabel(Calibration)
        self.label_17.setMinimumSize(QtCore.QSize(100, 50))
        self.label_17.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 1, 0, 1, 1)
        self.x_resolution = QtGui.QLabel(Calibration)
        self.x_resolution.setMinimumSize(QtCore.QSize(100, 50))
        self.x_resolution.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.x_resolution.setFont(font)
        self.x_resolution.setText(_fromUtf8(""))
        self.x_resolution.setObjectName(_fromUtf8("x_resolution"))
        self.gridLayout_2.addWidget(self.x_resolution, 1, 1, 1, 1)
        self.label_18 = QtGui.QLabel(Calibration)
        self.label_18.setMinimumSize(QtCore.QSize(100, 50))
        self.label_18.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 1, 2, 1, 1)
        self.y_resolution = QtGui.QLabel(Calibration)
        self.y_resolution.setMinimumSize(QtCore.QSize(100, 50))
        self.y_resolution.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.y_resolution.setFont(font)
        self.y_resolution.setText(_fromUtf8(""))
        self.y_resolution.setObjectName(_fromUtf8("y_resolution"))
        self.gridLayout_2.addWidget(self.y_resolution, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Calibration)
        QtCore.QMetaObject.connectSlotsByName(Calibration)

    def retranslateUi(self, Calibration):
        Calibration.setWindowTitle(_translate("Calibration", "Form", None))
        self.pushButton_grabImg.setText(_translate("Calibration", "开始采集", None))
        self.pushButton_save.setText(_translate("Calibration", "设为标准", None))
        self.label_1.setText(_translate("Calibration", "标准X角度:", None))
        self.label_2.setText(_translate("Calibration", "实际X角度:", None))
        self.label_3.setText(_translate("Calibration", "标准Y角度:", None))
        self.label_4.setText(_translate("Calibration", "实际Y角度:", None))
        self.label_5.setText(_translate("Calibration", "标准Z角度:", None))
        self.label_6.setText(_translate("Calibration", "实际Z角度:", None))
        self.label_7.setText(_translate("Calibration", "标准X坐标:", None))
        self.label_8.setText(_translate("Calibration", "实际X坐标:", None))
        self.label_9.setText(_translate("Calibration", "标准Y坐标:", None))
        self.label_10.setText(_translate("Calibration", "实际Y坐标:", None))
        self.label_19.setText(_translate("Calibration", "清晰度:", None))
        self.label_20.setText(_translate("Calibration", "亮度:", None))
        self.label_17.setText(_translate("Calibration", "X分辨率:", None))
        self.label_18.setText(_translate("Calibration", "Y分辨率:", None))

from pyqtgraph import GraphicsView
